"""added display_name

Revision ID: 96057179358c
Revises: 5a7b4077c8e6
Create Date: 2020-08-17 15:44:23.308058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96057179358c'
down_revision = '5a7b4077c8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
